language: node_js
node_js:
  - "11.10.1"
cache:
  directories:
  - node_modules
script:
  - npm8 test
  - npm8 run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token_5
  local_dir: build
on:
branch: master
